export {default as Contacts} from './Contacts/Contacts'
export {default as Home} from './Home/Home'
export {default as Messenger} from './Messenger/Messenger'
export {default as Phone} from './Phone/Phone'
export {default as Settings} from './Settings/Settings'